### ISSUE TITLE
Does sourcemod work on this ?

### ISSUE THREAD

**Issue by S1ncer3ly** [marcosolina/csgo_server#3]
sm is compatible with this repo ?

**Comment by marcosolina** [comment]
Yes it is

**Comment by marcosolina** [comment]
I have used this repo as base for another csgo server project which includes sourcemod. You just need to download sourcemod and add it in the specific folder. [Here how I did it in the other project](https://github.com/marcosolina/ixi_go/tree/main/CsgoServer/csgo/addons), the one which uses this one as base

**Comment by S1ncer3ly** [comment]
thanks alot for such a fast response +rep
