### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by S1ncer3ly** [marcosolina/csgo_server#4]
i installed everything there was no error untils its starting and giving me this error
![Screenshot 2022-04-25 013041](https://user-images.githubusercontent.com/70603773/164994362-172b0169-74a2-4fcc-a87a-1d6adbef514e.png)

srcds is in the path "F:\Servers\PC\steamapps\common\Counter-Strike Global Offensive Beta - Dedicated Server"

**Comment by marcosolina** [comment]
Hi @S1ncer3ly I think that there is an issue with the folder name. I can see you have spaces in the "folder name", this might cause problems. Can you please try to rename "F:\Servers\PC\steamapps\common\Counter-Strike Global Offensive Beta - Dedicated Server" into "F:\Servers\PC\steamapps\common\Counter-Strike_Global_Offensive_Beta_-_Dedicated_Server", [and don't forget to update the path in the script as well](https://github.com/marcosolina/csgo_server/blob/main/Windows/startServer.bat)

If still does not work please share the configuration of the script, and perhaps some screenshots of the files in the folder, thanks

**Comment by S1ncer3ly** [comment]
sure 1 min please and i will confirm

**Comment by S1ncer3ly** [comment]
![Screenshot 2022-04-25 014923](https://user-images.githubusercontent.com/70603773/164994971-ce3f856f-4aa4-4825-84f4-d0fbcd4ddcaa.png)
this is my file please have a look sorry for this trouble!

**Comment by S1ncer3ly** [comment]
![Uploading image.png…]()
this error is still there

**Comment by S1ncer3ly** [comment]
![Screenshot 2022-04-25 015038](https://user-images.githubusercontent.com/70603773/164995012-fcd20f9b-6dc8-4dde-b59c-d949f900b98e.png)
this error is still there
@marcosolina

**Comment by marcosolina** [comment]
Looking at your script, seems like that the CSGO_INSTALL_FOLDER_FOLDER has the wrong value. The value of that property should end with "csgoInstalDir". Have a look at this part of the video: https://www.youtube.com/watch?v=FK1UkkfipIs&t=370s and try to update the value. If you still have problems please share a screnshot of the folder that conatins this directory https://github.com/marcosolina/csgo_server/tree/main/csgoInstalDir

**Comment by S1ncer3ly** [comment]
FIXED !

**Comment by marcosolina** [comment]
Awesome

**Comment by S1ncer3ly** [comment]
i just changed my values in script and copied my server files two folder back in pc\ and it worked automatically!
thanks alot for your such quick response +rep again ! @marcosolina
